export const GET_TODOS_REQUEST = 'CREATE_TODO_REQUEST'
export const GET_TODOS_SUCCESS = 'CREATE_TODO_SUCCESS'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'

export const CREATE_TODO_REQUEST = 'GET_TODOS_REQUEST'

export const CLEAR_TODOS = 'CLEAR_TODOS'

export const ADD_TODO_LINK = 'ADD_TODO_LINK'
export const ADD_TODO_LINK_SUCCESS = 'ADD_TODO_LINK_SUCCESS'

export const GET_TODO_BY_ID_REQUEST = 'GET_TODO_BY_ID_REQUEST'
export const GET_TODO_BY_ID_SUCCESS = 'GET_TODO_BY_ID_SUCCESS'
