export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'

export const CLEAR_USER = 'CLEAR_USER'

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const IS_FETCHING_USERS = 'IS_FETCHING_USERS'
export const SUCCESS_FETCHED_USERS = 'SUCCESS_FETCHED_USERS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const SUCCESS_USER_BY_ID = 'SUCCESS_USER_BY_ID'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS'
